name: CI
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 4'

jobs:
  build:
    name: Continuous Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@950f159a49aa91f9323f36f1de81c7f6b5de9576 # v2.3.0
        with:
          version: latest

      - name: Set up Regal
        uses: StyraInc/setup-regal@33a142b1189004e0f14bf42b15972c67eecce776 # v1.0.0
        with:
          version: latest

      - name: format
        run: |
          opa fmt policies --fail --diff
          opa fmt samples --fail --diff
      - name: check
        run: opa check policies samples
      - name: lint
        run: regal lint --format=github policies samples
      - name: test
        run: opa test -v policies samples
